---

name: Build this Docker image

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '11 23 * * 0'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout Git repo
        uses: actions/checkout@v3
        with:
          ref: master
          path: git

      - name: Check build of image
        run: |
          sudo apt-get update
          sudo apt-get install -y jq tree

          built_file="./git/install/built.json"

          latest_info=$( curl https://api.github.com/repos/hakimel/reveal.js/releases/latest 2>/dev/null )
          version_tag=$( echo "${latest_info}" | jq -r '.tag_name')

          if [ ! -f "${built_file}" ]; then
            touch "${built_file}"
            echo "[]" > "${built_file}"
          fi

          if { jq -e --arg t "${version_tag}" '. | index($t)' < "${built_file}"; } then
            >&2 echo "Version ${version_tag} already built!"
            exit 1
          else
            >&2 echo "Version >>${version_tag}<< will be built"
            built=$( jq -e --arg t "${version_tag}" '. |= . + [$t]' < ${built_file} )
            echo "${built}" > "${built_file}"
            echo "BUILD_VERSION=${version_tag}" >> "$GITHUB_ENV"
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: devopsansiblede/revealjs:latest
          no-cache: true
          context: ./git/
          file: ./git/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_VERSION=${{ env.BUILD_VERSION }}

      - name: Push image
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/devopsansiblede/revealjs:latest
          dst: |
            docker.io/devopsansiblede/revealjs:${{ env.BUILD_VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Last Built
        run: sed -i -E "s/^[0-9]{4}-[0-9]{2}-[0-9]{2}\s+[0-9]{2}:[0-9]{2}:[0-9]{2}$/$( date +"%Y-%m-%d %T" )/" ./git/README.md

      - name: Commit last built information
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Last built
          commit_user_name: GitHub Actions
          commit_user_email: dev@macwinnie.me
          repository: ./git/

...
